-- Supabase Database Setup Script for Secure Video Platform

-- 1. Create Tables
CREATE TABLE public.videos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    video_path TEXT NOT NULL,
    owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    target_client_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.video_views (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    video_id UUID NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE,
    watch_count INT DEFAULT 0 NOT NULL,
    last_watched_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, video_id)
);

CREATE TABLE public.access_codes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    video_id UUID NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- Nullable if global
    is_used BOOLEAN DEFAULT false NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.video_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_codes ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies

-- Videos: Createurs can see and manage their own videos, Clients can see videos assigned to them
CREATE POLICY "Createurs can see their own videos" 
    ON public.videos FOR SELECT 
    USING (auth.uid() = owner_id);

CREATE POLICY "Clients can see videos assigned to them" 
    ON public.videos FOR SELECT 
    USING (auth.uid() = target_client_id);

CREATE POLICY "Createurs can insert their own videos" 
    ON public.videos FOR INSERT 
    WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Createurs can update their own videos" 
    ON public.videos FOR UPDATE 
    USING (auth.uid() = owner_id);

CREATE POLICY "Createurs can delete their own videos" 
    ON public.videos FOR DELETE 
    USING (auth.uid() = owner_id);

-- Video Views: Users can only see and update their own views
CREATE POLICY "Users can view their own video views" 
    ON public.video_views FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own video views" 
    ON public.video_views FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own video views" 
    ON public.video_views FOR UPDATE 
    USING (auth.uid() = user_id);

-- Access Codes: Users can see codes assigned to them, or global codes (user_id IS NULL)
CREATE POLICY "Users can view their access codes" 
    ON public.access_codes FOR SELECT 
    USING (auth.uid() = user_id OR user_id IS NULL);

-- Admin can do everything (Assuming we have a way to identify admin, 
-- for now we'll rely on Service Role key for admin server operations, 
-- which bypasses RLS).

-- 4. Storage Setup
-- Assuming a storage bucket named 'videos'
INSERT INTO storage.buckets (id, name, public) VALUES ('videos', 'videos', false) ON CONFLICT DO NOTHING;

-- Storage RLS: Deny all direct access from client, only allow signed URLs
CREATE POLICY "Deny all public access to videos" 
    ON storage.objects FOR SELECT 
    USING (bucket_id = 'videos' AND false); -- Only signed URLs generated by the server will work

-- 5. Helper Functions (Optional, but good for transactions)
-- Function to redeem code securely
CREATE OR REPLACE FUNCTION redeem_access_code(p_code TEXT, p_user_id UUID, p_video_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER -- Run as database owner to bypass RLS for this operation
AS $$
DECLARE
    v_code_record RECORD;
BEGIN
    -- Find the code
    SELECT * INTO v_code_record 
    FROM public.access_codes 
    WHERE code = p_code 
      AND video_id = p_video_id
      AND is_used = false
      AND (expires_at IS NULL OR expires_at > now())
      AND (user_id IS NULL OR user_id = p_user_id)
    FOR UPDATE; -- Lock the row

    IF NOT FOUND THEN
        RETURN FALSE;
    END IF;

    -- Mark code as used
    UPDATE public.access_codes SET is_used = true WHERE id = v_code_record.id;

    -- Update or Insert video view count
    INSERT INTO public.video_views (user_id, video_id, watch_count, last_watched_at)
    VALUES (p_user_id, p_video_id, 0, now())
    ON CONFLICT (user_id, video_id) 
    DO UPDATE SET 
        watch_count = 0, -- Reset watch count back to 0 so they can watch again
        last_watched_at = now();

    RETURN TRUE;
END;
$$;

-- 6. User Roles Table
CREATE TABLE public.user_roles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('admin', 'user', 'createur', 'client')) DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Policies for user_roles
CREATE POLICY "Users can view their own role" 
    ON public.user_roles FOR SELECT 
    USING (auth.uid() = user_id);

-- Admin check function
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

